# General settings
set -g mouse on
set -g default-terminal "tmux-256color"
set-window-option -g xterm-keys on

# remap prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v

# Unbind previous keys for splitting windows
unbind '"'
unbind %

# Move around windows with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Allow resizing with hjkl
bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

# Start index at 1
set -g base-index 1

# name windows by current dir
set -g status-interval 5
set -g automatic-rename on 
set -g automatic-rename-format '#{b:pane_current_path}'

# open new panes in the same directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# reload config file
bind r source-file ~/.config/tmux/tmux.conf

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_directory_text "#{pane_current_path}"

# Install from https://github.com/catppuccin/tmux
# Change all occourences of #T to #W in catppuccin_options_tmux.conf
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

